# permissions for end users to view tigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tig-viewer-role
rules:
- apiGroups:
  - game.example.com
  resources:
  - tigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - game.example.com
  resources:
  - tigs/status
  verbs:
  - get
